---
- name: Provision EC2 instance
  ec2:
    ec2_key_name: "srekey"
    ec2_instance_type: "t2.micro"
    ec2_image: "ami-12345678"  # Replace with your desired AMI ID
    ec2_region: "us-east-1"
    ec2_subnet_id: "subnet-12345678"
    assign_public_ip: yes
  register: ec2_instance