---
- name: Configure Nginx Web Server
  hosts: launched
  become: yes
  tasks:
    - name: Install Nginx
      yum:
        name: nginx
        state: present

    - name: Upload Nginx configuration file
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify: Restart Nginx

    - name: Upload default server configuration file
      template:
        src: default.conf.j2
        dest: /etc/nginx/conf.d/default.conf
      notify: Restart Nginx

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
